pdf:
	xelatex Einfuehrung_Maschinelles_Lernen.tex

pdf_follow_changes:
	latexmk -xelatex -pvc Einfuehrung_Maschinelles_Lernen.tex

check:
	lacheck Einfuehrung_Maschinelles_Lernen.tex

clean:
	rm -f *.aux  *.log .nav *.out *.snm *.toc *.nav *.fdb_latexmk *.fls *.xdv
